name: Docker Image CI

on:
  schedule:
    - cron: '0 17 * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-alpine-gccgo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Build the Docker image
      run: docker build alpine-abuild-gcc-go --file alpine-abuild-gcc-go/Dockerfile.alpine-gccgo --tag ghcr.io/jgowdy/alpine-gccgo:latest
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Publish the Docker image
      run: docker push ghcr.io/jgowdy/alpine-gccgo:latest
